// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: borrow_record.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from borrow_record.proto</summary>
public static partial class BorrowRecordReflection {

  #region Descriptor
  /// <summary>File descriptor for borrow_record.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BorrowRecordReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNib3Jyb3dfcmVjb3JkLnByb3RvIl4KDEJvcnJvd1JlY29yZBIRCgl1c2Vy",
          "X25hbWUYASABKAkSEQoJYm9va19uYW1lGAIgASgJEhMKC2JvcnJvd190aW1l",
          "GAMgASgJEhMKC3JldHVybl90aW1lGAQgASgJIjYKDUJvcnJvd1JlY29yZHMS",
          "JQoOYm9ycm93X3JlY29yZHMYASADKAsyDS5Cb3Jyb3dSZWNvcmRiBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BorrowRecord), global::BorrowRecord.Parser, new[]{ "UserName", "BookName", "BorrowTime", "ReturnTime" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BorrowRecords), global::BorrowRecords.Parser, new[]{ "BorrowRecords_" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BorrowRecord : pb::IMessage<BorrowRecord> {
  private static readonly pb::MessageParser<BorrowRecord> _parser = new pb::MessageParser<BorrowRecord>(() => new BorrowRecord());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BorrowRecord> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BorrowRecordReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecord() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecord(BorrowRecord other) : this() {
    userName_ = other.userName_;
    bookName_ = other.bookName_;
    borrowTime_ = other.borrowTime_;
    returnTime_ = other.returnTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecord Clone() {
    return new BorrowRecord(this);
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 1;
  private string userName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserName {
    get { return userName_; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "book_name" field.</summary>
  public const int BookNameFieldNumber = 2;
  private string bookName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string BookName {
    get { return bookName_; }
    set {
      bookName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "borrow_time" field.</summary>
  public const int BorrowTimeFieldNumber = 3;
  private string borrowTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string BorrowTime {
    get { return borrowTime_; }
    set {
      borrowTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "return_time" field.</summary>
  public const int ReturnTimeFieldNumber = 4;
  private string returnTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ReturnTime {
    get { return returnTime_; }
    set {
      returnTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BorrowRecord);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BorrowRecord other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserName != other.UserName) return false;
    if (BookName != other.BookName) return false;
    if (BorrowTime != other.BorrowTime) return false;
    if (ReturnTime != other.ReturnTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
    if (BookName.Length != 0) hash ^= BookName.GetHashCode();
    if (BorrowTime.Length != 0) hash ^= BorrowTime.GetHashCode();
    if (ReturnTime.Length != 0) hash ^= ReturnTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UserName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (BookName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(BookName);
    }
    if (BorrowTime.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(BorrowTime);
    }
    if (ReturnTime.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(ReturnTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (BookName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BookName);
    }
    if (BorrowTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BorrowTime);
    }
    if (ReturnTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ReturnTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BorrowRecord other) {
    if (other == null) {
      return;
    }
    if (other.UserName.Length != 0) {
      UserName = other.UserName;
    }
    if (other.BookName.Length != 0) {
      BookName = other.BookName;
    }
    if (other.BorrowTime.Length != 0) {
      BorrowTime = other.BorrowTime;
    }
    if (other.ReturnTime.Length != 0) {
      ReturnTime = other.ReturnTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          BookName = input.ReadString();
          break;
        }
        case 26: {
          BorrowTime = input.ReadString();
          break;
        }
        case 34: {
          ReturnTime = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class BorrowRecords : pb::IMessage<BorrowRecords> {
  private static readonly pb::MessageParser<BorrowRecords> _parser = new pb::MessageParser<BorrowRecords>(() => new BorrowRecords());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BorrowRecords> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BorrowRecordReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecords() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecords(BorrowRecords other) : this() {
    borrowRecords_ = other.borrowRecords_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BorrowRecords Clone() {
    return new BorrowRecords(this);
  }

  /// <summary>Field number for the "borrow_records" field.</summary>
  public const int BorrowRecords_FieldNumber = 1;
  private static readonly pb::FieldCodec<global::BorrowRecord> _repeated_borrowRecords_codec
      = pb::FieldCodec.ForMessage(10, global::BorrowRecord.Parser);
  private readonly pbc::RepeatedField<global::BorrowRecord> borrowRecords_ = new pbc::RepeatedField<global::BorrowRecord>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::BorrowRecord> BorrowRecords_ {
    get { return borrowRecords_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BorrowRecords);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BorrowRecords other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!borrowRecords_.Equals(other.borrowRecords_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= borrowRecords_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    borrowRecords_.WriteTo(output, _repeated_borrowRecords_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += borrowRecords_.CalculateSize(_repeated_borrowRecords_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BorrowRecords other) {
    if (other == null) {
      return;
    }
    borrowRecords_.Add(other.borrowRecords_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          borrowRecords_.AddEntriesFrom(input, _repeated_borrowRecords_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
