// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: user.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Csharp.Example.Model {

  /// <summary>Holder for reflection information generated from user.proto</summary>
  public static partial class UserReflection {

    #region Descriptor
    /// <summary>File descriptor for user.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp1c2VyLnByb3RvEh1wcm90b2J1Zi5jc2hhcnAuZXhhbXBsZS5tb2RlbCJi",
            "CgRVc2VyEgwKBG5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkSEwoJaXNE",
            "ZWZhdWx0GAMgASgISAASGAoOaXNBZG1pbnN0cmF0b3IYBCABKAhIAEILCgly",
            "b2xlX3R5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Csharp.Example.Model.User), global::Protobuf.Csharp.Example.Model.User.Parser, new[]{ "Name", "Password", "IsDefault", "IsAdminstrator" }, new[]{ "RoleType" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class User : pb::IMessage<User> {
    private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<User> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Csharp.Example.Model.UserReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User(User other) : this() {
      name_ = other.name_;
      password_ = other.password_;
      switch (other.RoleTypeCase) {
        case RoleTypeOneofCase.IsDefault:
          IsDefault = other.IsDefault;
          break;
        case RoleTypeOneofCase.IsAdminstrator:
          IsAdminstrator = other.IsAdminstrator;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public User Clone() {
      return new User(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isDefault" field.</summary>
    public const int IsDefaultFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsDefault {
      get { return roleTypeCase_ == RoleTypeOneofCase.IsDefault ? (bool) roleType_ : false; }
      set {
        roleType_ = value;
        roleTypeCase_ = RoleTypeOneofCase.IsDefault;
      }
    }

    /// <summary>Field number for the "isAdminstrator" field.</summary>
    public const int IsAdminstratorFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAdminstrator {
      get { return roleTypeCase_ == RoleTypeOneofCase.IsAdminstrator ? (bool) roleType_ : false; }
      set {
        roleType_ = value;
        roleTypeCase_ = RoleTypeOneofCase.IsAdminstrator;
      }
    }

    private object roleType_;
    /// <summary>Enum of possible cases for the "role_type" oneof.</summary>
    public enum RoleTypeOneofCase {
      None = 0,
      IsDefault = 3,
      IsAdminstrator = 4,
    }
    private RoleTypeOneofCase roleTypeCase_ = RoleTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoleTypeOneofCase RoleTypeCase {
      get { return roleTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRoleType() {
      roleTypeCase_ = RoleTypeOneofCase.None;
      roleType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as User);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(User other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      if (IsDefault != other.IsDefault) return false;
      if (IsAdminstrator != other.IsAdminstrator) return false;
      if (RoleTypeCase != other.RoleTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (roleTypeCase_ == RoleTypeOneofCase.IsDefault) hash ^= IsDefault.GetHashCode();
      if (roleTypeCase_ == RoleTypeOneofCase.IsAdminstrator) hash ^= IsAdminstrator.GetHashCode();
      hash ^= (int) roleTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (roleTypeCase_ == RoleTypeOneofCase.IsDefault) {
        output.WriteRawTag(24);
        output.WriteBool(IsDefault);
      }
      if (roleTypeCase_ == RoleTypeOneofCase.IsAdminstrator) {
        output.WriteRawTag(32);
        output.WriteBool(IsAdminstrator);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (roleTypeCase_ == RoleTypeOneofCase.IsDefault) {
        size += 1 + 1;
      }
      if (roleTypeCase_ == RoleTypeOneofCase.IsAdminstrator) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(User other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      switch (other.RoleTypeCase) {
        case RoleTypeOneofCase.IsDefault:
          IsDefault = other.IsDefault;
          break;
        case RoleTypeOneofCase.IsAdminstrator:
          IsAdminstrator = other.IsAdminstrator;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            IsDefault = input.ReadBool();
            break;
          }
          case 32: {
            IsAdminstrator = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
